---
# Ref: https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: false # default is true
contact_links:
  - name: Help and Support
    url: https://matrix.to/#/#aap_config_as_code:ansible.com
    about: Matrix room for questions. (or go to the forums)
  - name: Feature requests
    url: https://forum.ansible.com/tag/infra-config-as-code
    about: Any kind of questions or ideas should go on the forum.
  - name: Ansible Code of Conduct
    url: https://docs.ansible.com/ansible/latest/community/code_of_conduct.html
    about: Be nice to other members of the community. Behave.
