---
- name: "Get list of files inside {{ filetree_controller_roles }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_roles }}"
    file_type: file
    recurse: true
  register: __list_files_controller_roles

- name: "Read Roles definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_roles_definitions_item.path }}"
  loop: "{{ __list_files_controller_roles.files }}"
  loop_control:
    loop_var: __read_roles_definitions_item
  register: __contents_filetree_controller_roles
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_controller_roles"

- name: "Set Roles Data Structure"
  ansible.builtin.set_fact:
    controller_roles: >-
      {{
        __contents_filetree_controller_roles.results |
        rejectattr('ansible_facts.controller_roles', 'undefined') |
        map(attribute='ansible_facts.controller_roles') |
        ansible.builtin.flatten
      }}
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __contents_filetree_controller_roles.results
...
