---
- name: "Get list of files inside {{ filetree_controller_teams }}"
  ansible.builtin.find:
    paths: "{{ filetree_controller_teams }}"
    file_type: file
    recurse: true
  register: __list_files_controller_teams

- name: "Read Teams definitions"
  ansible.builtin.include_vars:
    file: "{{ __read_teams_definitions_item.path }}"
  loop: "{{ __list_files_controller_teams.files }}"
  loop_control:
    loop_var: __read_teams_definitions_item
  register: __contents_filetree_controller_teams
  failed_when: "'VARIABLE IS NOT DEFINED' in __contents_filetree_controller_teams"

- name: "Set Roles Data Structure"
  ansible.builtin.set_fact:
    controller_roles: >-
      {{
        __contents_filetree_controller_teams.results |
        rejectattr('ansible_facts.controller_teams', 'undefined') |
        map(attribute='ansible_facts.controller_teams') |
        ansible.builtin.flatten
      }}
  no_log: "{{ controller_configuration_filetree_read_secure_logging }}"
  when: __contents_filetree_controller_teams.results
...
