---
name: Test collection with AWX matrix
on:
  push:
    branches:
      - '*_'
      - devel
    tags:
      - '*_'  # ending underscore for trying things
      - 'v[0-9]+.[0-9]+.[0-9]+'  # final version
      - 'v[0-9]+.[0-9]+.[0-9]+[abrc]+[0-9]+'  # alpha, beta, release candidate (rc)
      - 'v[0-9]+.[0-9]+.[0-9]+.dev[0-9]+'  # development versions
  pull_request:

jobs:
  ci_standalone:
    strategy:
      fail-fast: false
      matrix:
        awx_version:
          - devel
          - 24.2.0
          - 23.9.0
          - 22.7.0
    uses: "./.github/workflows/ci_standalone_versioned.yml"
    with:
      awx_version: ${{ matrix.awx_version }}
      gh_ref: ${{ github.event.pull_request.head.sha || github.sha }}
...
